name: Security Gates 🛡️

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Workflow
        run: echo "Validation successful"

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@99397e9be8a957d447c3b402e1e8c026d731ba29
    permissions:
      actions: read
      contents: read
      security-events: write
    secrets: inherit
